### ISSUE TITLE
Got a error when try to lunch

### ISSUE THREAD

**Issue by ido335** [evaera/RoVer#220]
Error: Cannot find module 'request-promise'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Professional\Downloads\RoVer-master\RoVer-master\src\index.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

please help me

**Comment by evaera** [comment]
Please use the official version at RoVer.link, we do not provide support for self-hosting beyond the instructions found on the README.
