### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Tanmanthevan** [evaera/RoVer#259]
I just copied a part of the code (for only myself) and when I try to do node . the console replies "(node:51604) UnhandledPromiseRejectionWarning: TypeError: this.fetchUser is not a function
    at CommandoClient.<anonymous> (C:\Windows\System32\vBot\node_modules\discord.js-commando\src\client.js:84:11)
    at Object.onceWrapper (events.js:417:28)
    at CommandoClient.emit (events.js:323:22)
    at WebSocketManager.triggerClientReady (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:433:17)
    at WebSocketManager.checkShardsReady (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:417:10)
    at WebSocketShard.<anonymous> (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:199:14)
    at WebSocketShard.emit (events.js:311:20)
    at WebSocketShard.checkReady (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:467:12)
    at WebSocketShard.onPacket (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:439:16)
    at WebSocketShard.onMessage (C:\Windows\System32\vBot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Windows\System32\vBot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:311:20)
    at Receiver.receiverOnMessage (C:\Windows\System32\vBot\node_modules\ws\lib\websocket.js:801:20)
    at Receiver.emit (events.js:311:20)
    at Receiver.dataMessage (C:\Windows\System32\vBot\node_modules\ws\lib\receiver.js:436:14)
    at Receiver.getData (C:\Windows\System32\vBot\node_modules\ws\lib\receiver.js:366:17)
    at Receiver.startLoop (C:\Windows\System32\vBot\node_modules\ws\lib\receiver.js:142:22)
    at Receiver._write (C:\Windows\System32\vBot\node_modules\ws\lib\receiver.js:77:10)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Receiver.Writable.write (_stream_writable.js:316:11)
    at TLSSocket.socketOnData (C:\Windows\System32\vBot\node_modules\ws\lib\websocket.js:876:35)" Could you help me?

**Comment by PhoenixShay** [comment]
You're doing one of the following:
- Using wrong node version
- Using wrong discord.js version
- Edited the code or made a change to the official repo

[We have 3 tests on different node versions that run every time a commit is made](https://github.com/evaera/RoVer/actions), this is user-error.

**Comment by Tanmanthevan** [comment]
I did not edit the code, and could you tell me what discord.js and node version to use?

**Comment by coexperience** [comment]
The error seems to be caused by you using an incorrect version of Commando. Make sure your using `npm install` so it pulls from the package.json, rather than you manually installing things from NPM.

**Comment by Tanmanthevan** [comment]
But, to install commando I've done `npm i commando` in the terminal, so I don't see what could be the problem. Should I install it in a different way?

**Comment by PhoenixShay** [comment]
Please follow the self hosting instructions in the readme, we cannot offer any support beyond that.
