### ISSUE TITLE
Bot not starting... 

### ISSUE THREAD

**Issue by Buckskin7** [evaera/RoVer#343]
`internal/fs/utils.js:269
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/StyraxBot/index.js'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (/run_dir/interp.js:195:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/StyraxBot/index.js'
}`

**Comment by Buckskin7** [comment]
I've done node ./src/index.js but it still won't start.

**Comment by Rythian2277** [comment]
We do not offer support for self-hosting RoVer.
