### ISSUE TITLE
Bot Starting Error

### ISSUE THREAD

**Issue by JaedonLau** [evaera/RoVer#360]
So recently just now morning, i got my bot started up, but it went offline when night comes, and im getting this new error while starting the bot

 Unhandled rejection StatusCodeError: 504 - "<html>\n<head><title>504 Gateway Time-out</title></head>\n<body bgcolor=\"white\">\n<center><h1>504 Gateway Time-out</h1></center>\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\n</body>\n</html>\n"
    at new StatusCodeError (/home/runner/RoVer/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/runner/RoVer/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/runner/RoVer/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/runner/RoVer/node_modules/request/request.js:188:22)
    at Request.emit (events.js:375:28)
    at Request.<anonymous> (/home/runner/RoVer/node_modules/request/request.js:1171:10)
    at Request.emit (events.js:375:28)
    at IncomingMessage.<anonymous> (/home/runner/RoVer/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:481:28)
    at IncomingMessage.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21

**Comment by Rythian2277** [comment]
For future record, support for self hosting is not available. It is recommended that you only self host this bot if you are experienced with JavaScript and Roblox APIs
