### ISSUE TITLE
idk halp!

### ISSUE THREAD

**Issue by ColtenLange22** [evaera/RoVer#48]
fs.js:968
  binding.stat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, stat '/Users/coltenlange/Desktop/bots/Bots in use/RoVer-master/Shard.js'
    at Object.fs.statSync (fs.js:968:11)
    at new ShardingManager (/Users/coltenlange/Desktop/bots/Bots in use/RoVer-master/node_modules/discord.js/src/sharding/ShardingManager.js:39:22)
    at Object.<anonymous> (/Users/coltenlange/Desktop/bots/Bots in use/RoVer-master/src/index.js:8:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)

**Comment by ColtenLange22** [comment]
ermmmm why?
